### ISSUE TITLE
`parsePrompt(...)` is missing documentation

### ISSUE THREAD

**Issue by JensRantil** [fimblo/prompt2#13]
Based on the looks of it, and how it is being used in the `main()` function, it feels like https://github.com/fimblo/prompt2/blob/8c817cdfecd3a751bb9b0f1c213373e80b2b32e8/src/prompt.c#L73 is a core function. Maybe it should be documented? I struggled to fully understand what it does.

**Comment by fimblo** [comment]
Oh it most certainly is, and should be.
Previously I tried to document things properly, but the code kept on changing and keeping the docs up-to-date was taking a lot of my time/energy. I guess I opted to stop documenting instead of documenting the most important things. 

Good that you pointed this out, thx.
