### ISSUE TITLE
Aliases in the config file

### ISSUE THREAD

**Issue by JensRantil** [fimblo/prompt2#43]
@fimblo shared a short demo of this recently with me. He mentioned that the config files can be a bit bloated with a lot of escape codes and long lines. This issue is a proposal to support (reusable) aliases (like, constants) that can be referred to from a prompt. This _might_ simplify the prompts.

Next level could also be to have certain hardcoded aliases for common things (colors? Bold text?) to make it easier to create a prompt.

Creating this ticket as it's a potential future improvement!

**Comment by fimblo** [comment]
I was thinking along these lines before, but I think the way forward is to make it so that we don't need to see the bloated config at all (unless one actually chooses to). Instead, I think creating a tool which helps create a prompt might be the way forward.

One thing I'm quite sure that I will do though is having aliases for colours.

**Comment by fimblo** [comment]
See GH-28
