### ISSUE TITLE
A little unclear which functions in header file are considered exported and which ones aren't

### ISSUE THREAD

**Issue by JensRantil** [fimblo/prompt2#7]
I am reading https://github.com/fimblo/prompt2/blob/8c817cdfecd3a751bb9b0f1c213373e80b2b32e8/src/get-status.h and I find it a little unclear which functions in header file are considered exported and which ones aren't. For example, should https://github.com/fimblo/prompt2/blob/8c817cdfecd3a751bb9b0f1c213373e80b2b32e8/src/get-status.h#L74 be exported to an application using this? It looks like it modifies `CurrentState`. Given that https://github.com/fimblo/prompt2/blob/8c817cdfecd3a751bb9b0f1c213373e80b2b32e8/src/test-functions.c only uses `initialiseState(...)`, `gatherGitContext(...)` & `cleanupResources(...)` maybe those are the only functions that needs to be exported?

One idea is to have one header file for exported functions and another file(s?) for the internal functions.

**Comment by fimblo** [comment]
Yeah. Initially, most functions were exported since I felt that I wanted it to be a generic library. But I recently decided to make it less generic, and I'm shifting functions to become private - with a small handful of exported functions. I started transforming it from one to the other when I got distracted and did other things. `gatherAWSContext` is one of those, I think.
